name: Relentless
favicon: null
layout_spectrum: 0.4448837600648403
typography_spectrum: 0.17157017695717514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5263232982251793
  lightness: 0.6222390923649073
  saturation: 0.09881578478962183
  rhythmicContrast: 0.5470789801329374
purpose: []
